services:
  backend:
    extends:
      service: backend
      file: docker-compose.base.yaml
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
        - ./envs/.env.local
    volumes:
      - ./envs/.env.local:/backend/.env
  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.local
    ports:
      - "5432:5432"

networks:
  main:

volumes:
  fast_quora_postgres_data:
