services:
  backend:
    image: ml06py/fast_quora:latest
    extends:
      service: backend
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./envs/.env.prod:/backend/.env
  celery:
    image: ml06py/fast_quora:latest
    extends:
      service: celery
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./envs/.env.prod:/backend/.env
  celery-beat:
    image: ml06py/fast_quora:latest
    extends:
      service: celery-beat
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./envs/.env.prod:/backend/.env
  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
  elastic:
    extends:
      service: elastic
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
  redis:
    extends:
      service: redis
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
  jaeger:
    extends:
      service: jaeger
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.local

networks:
  main:

volumes:
  fast_quora_postgres_data:
  fast_quora_elastic_data:
