services:
  backend:
    image: ml06py/fast_quora:latest
    extends:
      service: backend
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod
  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yaml
    env_file:
      - ./envs/.env.prod

networks:
  main:

volumes:
  fast_quora_postgres_data:
