services:
  backend:
    extends:
      service: backend
      file: docker-compose.base.yaml
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
        - ./envs/.env.local

networks:
  main:
