"""Add user model

Revision ID: 8c1152571ac8
Revises:
Create Date: 2024-08-18 08:39:58.060957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8c1152571ac8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), default=sa.text("uuid_generate_v4()")),
        sa.Column("email", sa.String, nullable=False),
        sa.Column("nickname", sa.String, nullable=False),
        sa.Column("biography", sa.String(length=255), nullable=True, server_default=""),
        sa.Column("password", sa.String, nullable=False),
        sa.Column("date_joined", sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("uuid", name="users_uuid_key"),
        sa.UniqueConstraint("email", name="users_email_key"),
        sa.UniqueConstraint("nickname", name="users_nickname_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
