apiVersion: v1
kind: Service

metadata:
  name: elastic
  labels:
    app: fast-quora-elastic

spec:
  ports:
    - port: 9300
      targetPort: 9300
      name: transport
    - port: 9200
      targetPort: 9200
      name: http
  selector:
    app: fast-quora-elastic

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-quora-elastic
  labels:
    app: fast-quora-elastic

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-quora-elastic
  template:
    metadata:
      labels:
        app: fast-quora-elastic
    spec:
      containers:
        - name: fast-quora-elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
          ports:
            - containerPort: 9300
            - containerPort: 9200
          envFrom:
            - configMapRef:
                name: fast-quora-env
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 20
            periodSeconds: 10
