apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-quora-jaeger
  labels:
    app: fast-quora-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-quora-jaeger
  template:
    metadata:
      labels:
        app: fast-quora-jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.32
          ports:
            - containerPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: fast-quora-jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
