apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-quora-postgres-dp
  labels:
    app: fast-quora-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-quora-postgres
  template:
    metadata:
      labels:
        app: fast-quora-postgres
    spec:
      containers:
        - name: fast-quora-postgres
          image: postgres:15.4-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: fast-quora-env
---

apiVersion: v1
kind: Service

metadata:
  name: postgres
  labels:
    app: fast-quora-postgres

spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: fast-quora-postgres
