apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-quora-redis-dp
  labels:
    app: fast-quora-redis

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-quora-redis

  template:
    metadata:
      labels:
        app: fast-quora-redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
          resizePolicy:
            - resourceName: memory
              restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: fast-quora-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
